services:
  - type: web
    name: redpanda
    env: docker
    plan: free
    autoDeploy: true
    region: oregon
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: ""
    ports:
      - port: 9092
        protocol: TCP
